use std::collections::HashSet;

use super::{NerDetector, NerSpan};

const CONTEXT_WINDOW: usize = 80;
const CONTEXT_BOOST: f64 = 0.15;

const CONTEXT_KEYWORDS: &[&str] = &[
    "passenger",
    "passager",
    "passagère",
    "name",
    "nom",
    "pilot",
    "pilote",
    "captain",
    "capitaine",
    "commandant",
    "crew",
    "équipage",
    "equipage",
    "copilot",
    "copilote",
    "member",
    "membre",
    "contact",
    "person",
    "personne",
    "client",
    "patient",
    "employee",
    "employé",
    "employée",
    "salarié",
    "user",
    "utilisateur",
    "utilisatrice",
    "author",
    "auteur",
];

const TITLES_FR: &[&str] = &[
    "M.",
    "Mme",
    "Mlle",
    "Dr",
    "Pr",
    "Me",
    "Capitaine",
    "Commandant",
    "Lieutenant",
    "Colonel",
    "Général",
];

const TITLES_EN: &[&str] = &[
    "Mr", "Mr.", "Mrs", "Mrs.", "Ms", "Ms.", "Miss", "Dr", "Dr.", "Prof", "Prof.", "Captain",
    "Cpt", "Lt",
];

// Top 2000 French first names from INSEE (generated by scripts/build_names.py)
include!("names_insee.rs");

// Top English first names
const ENGLISH_FIRST_NAMES: &[&str] = &[
    "Aaron",
    "Adam",
    "Adrian",
    "Alan",
    "Albert",
    "Alex",
    "Alexander",
    "Alfred",
    "Alice",
    "Alison",
    "Amanda",
    "Amber",
    "Amy",
    "Andrea",
    "Andrew",
    "Angela",
    "Ann",
    "Anna",
    "Anne",
    "Anthony",
    "Arthur",
    "Ashley",
    "Barbara",
    "Barry",
    "Benjamin",
    "Bernard",
    "Betty",
    "Beverly",
    "Bill",
    "Billy",
    "Bobby",
    "Bradley",
    "Brandon",
    "Brenda",
    "Brian",
    "Bruce",
    "Bryan",
    "Carl",
    "Carol",
    "Caroline",
    "Carolyn",
    "Catherine",
    "Charles",
    "Charlotte",
    "Cheryl",
    "Chris",
    "Christina",
    "Christine",
    "Christopher",
    "Cindy",
    "Claire",
    "Clara",
    "Clarence",
    "Craig",
    "Cynthia",
    "Dale",
    "Daniel",
    "Danny",
    "Darren",
    "David",
    "Dawn",
    "Dean",
    "Deborah",
    "Debra",
    "Dennis",
    "Diana",
    "Diane",
    "Donald",
    "Donna",
    "Dorothy",
    "Douglas",
    "Dylan",
    "Earl",
    "Edward",
    "Eileen",
    "Eleanor",
    "Elizabeth",
    "Ellen",
    "Emily",
    "Emma",
    "Eric",
    "Ernest",
    "Ethan",
    "Eugene",
    "Eva",
    "Evelyn",
    "Frances",
    "Francis",
    "Frank",
    "Fred",
    "Frederick",
    "Gabriel",
    "Gary",
    "George",
    "Gerald",
    "Gloria",
    "Gordon",
    "Grace",
    "Graham",
    "Gregory",
    "Harold",
    "Harry",
    "Heather",
    "Helen",
    "Henry",
    "Howard",
    "Ian",
    "Irene",
    "Isaac",
    "Jack",
    "Jacob",
    "Jacqueline",
    "James",
    "Jane",
    "Janet",
    "Janice",
    "Jason",
    "Jean",
    "Jeffrey",
    "Jennifer",
    "Jeremy",
    "Jerry",
    "Jesse",
    "Jessica",
    "Jill",
    "Jimmy",
    "Joan",
    "Joanne",
    "Joe",
    "Joel",
    "John",
    "Jonathan",
    "Jordan",
    "Joseph",
    "Joshua",
    "Joyce",
    "Judith",
    "Judy",
    "Julia",
    "Julie",
    "Justin",
    "Karen",
    "Katherine",
    "Kathleen",
    "Kathryn",
    "Kathy",
    "Keith",
    "Kelly",
    "Kenneth",
    "Kevin",
    "Kimberly",
    "Kyle",
    "Larry",
    "Laura",
    "Lauren",
    "Lawrence",
    "Lee",
    "Leonard",
    "Leslie",
    "Lillian",
    "Linda",
    "Lisa",
    "Lois",
    "Lorraine",
    "Louis",
    "Louise",
    "Lucas",
    "Lucy",
    "Lynn",
    "Madison",
    "Margaret",
    "Maria",
    "Marilyn",
    "Marion",
    "Mark",
    "Martha",
    "Martin",
    "Mary",
    "Mason",
    "Matthew",
    "Maureen",
    "Megan",
    "Melissa",
    "Michael",
    "Michelle",
    "Mildred",
    "Nancy",
    "Natalie",
    "Nathan",
    "Nicholas",
    "Nicole",
    "Noah",
    "Norma",
    "Norman",
    "Oliver",
    "Olivia",
    "Oscar",
    "Pamela",
    "Patricia",
    "Patrick",
    "Paul",
    "Paula",
    "Peggy",
    "Peter",
    "Philip",
    "Phillip",
    "Phyllis",
    "Rachel",
    "Ralph",
    "Randy",
    "Raymond",
    "Rebecca",
    "Richard",
    "Rita",
    "Robert",
    "Robin",
    "Rodney",
    "Roger",
    "Ronald",
    "Rose",
    "Roy",
    "Ruby",
    "Russell",
    "Ruth",
    "Ryan",
    "Sally",
    "Samantha",
    "Samuel",
    "Sandra",
    "Sara",
    "Sarah",
    "Scott",
    "Sean",
    "Sharon",
    "Sheila",
    "Shirley",
    "Sophia",
    "Stephanie",
    "Stephen",
    "Steven",
    "Stuart",
    "Susan",
    "Suzanne",
    "Tammy",
    "Teresa",
    "Terry",
    "Theresa",
    "Thomas",
    "Timothy",
    "Tina",
    "Todd",
    "Tony",
    "Tracy",
    "Tyler",
    "Valerie",
    "Victor",
    "Victoria",
    "Vincent",
    "Virginia",
    "Walter",
    "Wanda",
    "Wayne",
    "Wendy",
    "William",
    "Willie",
    "Zachary",
];

pub struct HeuristicNerDetector {
    first_names: HashSet<String>,
    last_names: HashSet<String>,
    min_score: f64,
}

impl HeuristicNerDetector {
    pub fn new() -> Self {
        let mut first_names: HashSet<String> = HashSet::new();
        for name in INSEE_FIRST_NAMES {
            first_names.insert(name.to_string());
        }
        for name in ENGLISH_FIRST_NAMES {
            first_names.insert(name.to_string());
        }

        let mut last_names: HashSet<String> = HashSet::new();

        // Load custom names from ~/.anon/firstnames.txt and ~/.anon/lastnames.txt
        if let Some(home) = dirs::home_dir() {
            let anon_dir = home.join(".anon");
            if let Ok(content) = std::fs::read_to_string(anon_dir.join("firstnames.txt")) {
                for line in content.lines() {
                    let name = line.trim();
                    if !name.is_empty() && !name.starts_with('#') {
                        first_names.insert(name.to_string());
                    }
                }
            }
            if let Ok(content) = std::fs::read_to_string(anon_dir.join("lastnames.txt")) {
                for line in content.lines() {
                    let name = line.trim();
                    if !name.is_empty() && !name.starts_with('#') {
                        last_names.insert(name.to_string());
                    }
                }
            }
        }

        Self {
            first_names,
            last_names,
            min_score: 0.5,
        }
    }

    fn has_context(&self, text: &str, start: usize, end: usize) -> bool {
        let mut ws = start.saturating_sub(CONTEXT_WINDOW);
        let mut we = (end + CONTEXT_WINDOW).min(text.len());
        while !text.is_char_boundary(ws) {
            ws += 1;
        }
        while !text.is_char_boundary(we) {
            we -= 1;
        }
        let window = text[ws..we].to_lowercase();
        CONTEXT_KEYWORDS.iter().any(|kw| window.contains(kw))
    }

    fn is_capitalized_word(word: &str) -> bool {
        let mut chars = word.chars();
        match chars.next() {
            Some(c) if c.is_uppercase() => {
                // After a hyphen, next char must be uppercase (e.g. "Jean-Pierre")
                // to avoid matching verbs like "Pourrais-tu"
                let mut after_hyphen = false;
                for ch in chars {
                    if after_hyphen {
                        if !ch.is_uppercase() {
                            return false;
                        }
                        after_hyphen = false;
                    } else if ch == '-' || ch == '\'' {
                        after_hyphen = true;
                    } else if !ch.is_lowercase() {
                        return false;
                    }
                }
                !after_hyphen // reject trailing hyphen
            }
            _ => false,
        }
    }

    /// Check if a word looks like a last name: either Capitalized or ALL-CAPS
    /// (French convention: "DUPONT", "LEROY", "MARTIN").
    fn is_name_word(word: &str) -> bool {
        if word.is_empty() || word.len() < 2 {
            return false;
        }
        // ALL-CAPS: only letters/hyphens/apostrophes, at least 2 alphabetic chars
        if word
            .chars()
            .all(|c| c.is_uppercase() || c == '-' || c == '\'')
            && word.chars().filter(|c| c.is_alphabetic()).count() >= 2
        {
            // Reject abbreviations (DSI, CIO, CLI, etc.)
            return !crate::patterns::CREW_CODE_BLOCKLIST.contains(&word);
        }
        Self::is_capitalized_word(word)
    }

    fn detect_title_patterns(&self, text: &str) -> Vec<NerSpan> {
        let mut spans = Vec::new();

        for title in TITLES_FR.iter().chain(TITLES_EN.iter()) {
            let mut search_from = 0;
            while let Some(pos) = text[search_from..].find(title) {
                let abs_pos = search_from + pos;
                // Must be at word boundary
                if abs_pos > 0 {
                    let prev = text[..abs_pos].chars().last().unwrap();
                    if prev.is_alphanumeric() {
                        search_from = abs_pos + title.len();
                        continue;
                    }
                }

                let after_title = abs_pos + title.len();
                // Collect capitalized words after the title
                let rest = &text[after_title..];
                let mut name_parts: Vec<&str> = Vec::new();
                let mut offset = 0;

                // Skip spaces (not newlines — names must be on the same line as the title)
                for ch in rest.chars() {
                    if ch == ' ' {
                        offset += 1;
                    } else {
                        break;
                    }
                }

                // Only look at the rest of the current line
                let rest_line = rest[offset..].split('\n').next().unwrap_or("");
                for word in rest_line.split_whitespace().take(3) {
                    let clean_word = word.trim_end_matches(|c: char| c.is_ascii_punctuation());
                    if Self::is_name_word(clean_word) {
                        name_parts.push(clean_word);
                    } else {
                        break;
                    }
                }

                if !name_parts.is_empty() {
                    let full_name = name_parts.join(" ");
                    let name_start = after_title + offset;
                    let name_end = name_start + full_name.len();

                    let base_score = if name_parts.len() >= 2 { 0.75 } else { 0.65 };
                    let score = if self.has_context(text, abs_pos, name_end) {
                        (base_score + CONTEXT_BOOST).min(1.0)
                    } else {
                        base_score
                    };

                    if score >= self.min_score {
                        spans.push(NerSpan {
                            text: full_name,
                            start: name_start,
                            end: name_end,
                            score,
                            label: "PERSON".to_string(),
                        });
                    }
                }

                search_from = abs_pos + title.len();
            }
        }

        spans
    }

    fn detect_dictionary_patterns(&self, text: &str) -> Vec<NerSpan> {
        let mut spans = Vec::new();
        let words: Vec<(usize, &str)> = {
            let mut result = Vec::new();
            let mut pos = 0;
            while pos < text.len() {
                // Skip whitespace
                match text[pos..].find(|c: char| !c.is_whitespace()) {
                    Some(skip) => pos += skip,
                    None => break,
                }
                // Find end of word
                let end = pos
                    + text[pos..]
                        .find(|c: char| c.is_whitespace())
                        .unwrap_or(text.len() - pos);
                result.push((pos, &text[pos..end]));
                pos = end;
            }
            result
        };

        for i in 0..words.len() {
            let (start, word) = words[i];
            // Strip leading and trailing punctuation for lookup (handles @mentions, trailing periods)
            let clean = word
                .trim_start_matches(|c: char| c.is_ascii_punctuation())
                .trim_end_matches(|c: char| c.is_ascii_punctuation());

            if self.first_names.contains(clean) {
                // Adjust start for stripped leading punctuation
                let leading_stripped = word.len()
                    - word
                        .trim_start_matches(|c: char| c.is_ascii_punctuation())
                        .len();
                let clean_start = start + leading_stripped;
                // Look for following capitalized word(s) to form full name
                let mut name_parts = vec![clean];
                let mut end = clean_start + clean.len();
                let mut has_known_lastname = false;

                for j in (i + 1)..words.len().min(i + 3) {
                    let (_, next_word) = words[j];
                    // Stop if the raw word starts a new line (it's a sentence continuation, not a name)
                    let gap = &text[end..words[j].0];
                    if gap.contains('\n') {
                        break;
                    }
                    let next_clean = next_word.trim_end_matches(|c: char| c.is_ascii_punctuation());
                    if Self::is_name_word(next_clean) {
                        if self.last_names.contains(next_clean) {
                            has_known_lastname = true;
                        }
                        name_parts.push(next_clean);
                        end = words[j].0 + next_clean.len();
                    } else {
                        break;
                    }
                }

                if name_parts.len() >= 2 {
                    // Firstname + lastname: confident match
                    // Higher confidence if lastname is in the custom list
                    let full_name = text[clean_start..end].to_string();

                    let base_score = if has_known_lastname { 0.70 } else { 0.55 };
                    let score = if self.has_context(text, clean_start, end) {
                        (base_score + CONTEXT_BOOST).min(1.0)
                    } else {
                        base_score
                    };

                    if score >= self.min_score {
                        spans.push(NerSpan {
                            text: full_name,
                            start: clean_start,
                            end,
                            score,
                            label: "PERSON".to_string(),
                        });
                    }
                } else if name_parts.len() == 1
                    && self.has_context(text, clean_start, clean_start + clean.len())
                {
                    // Standalone known first name with nearby context keyword
                    // e.g. "User: Alice", "passenger Alice", "contact Alice"
                    let name_end = clean_start + clean.len();
                    spans.push(NerSpan {
                        text: clean.to_string(),
                        start: clean_start,
                        end: name_end,
                        score: 0.50,
                        label: "PERSON".to_string(),
                    });
                }
            }
        }

        spans
    }
}

impl NerDetector for HeuristicNerDetector {
    fn detect_persons(&self, text: &str) -> Vec<NerSpan> {
        let mut spans = self.detect_title_patterns(text);
        let dict_spans = self.detect_dictionary_patterns(text);

        // Merge, keeping non-overlapping spans (title patterns take priority)
        for ds in dict_spans {
            let overlaps = spans.iter().any(|s| ds.start < s.end && ds.end > s.start);
            if !overlaps {
                spans.push(ds);
            }
        }

        spans
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_title_french_m() {
        let det = HeuristicNerDetector::new();
        let spans = det.detect_persons("M. Dupont est arrivé.");
        assert_eq!(spans.len(), 1);
        assert_eq!(spans[0].text, "Dupont");
        assert_eq!(spans[0].label, "PERSON");
    }

    #[test]
    fn test_title_french_mme() {
        let det = HeuristicNerDetector::new();
        let spans = det.detect_persons("Mme Martin est en retard.");
        assert_eq!(spans.len(), 1);
        assert_eq!(spans[0].text, "Martin");
    }

    #[test]
    fn test_title_english_dr() {
        let det = HeuristicNerDetector::new();
        let spans = det.detect_persons("Dr. Smith examined the patient.");
        assert_eq!(spans.len(), 1);
        assert_eq!(spans[0].text, "Smith");
    }

    #[test]
    fn test_title_with_full_name() {
        let det = HeuristicNerDetector::new();
        let spans = det.detect_persons("Capitaine Jean Dupont a décollé.");
        assert_eq!(spans.len(), 1);
        assert_eq!(spans[0].text, "Jean Dupont");
        assert!(spans[0].score >= 0.7);
    }

    #[test]
    fn test_dictionary_french_name() {
        let det = HeuristicNerDetector::new();
        let spans = det.detect_persons("Contact Philippe Martin pour les détails.");
        assert_eq!(spans.len(), 1);
        assert_eq!(spans[0].text, "Philippe Martin");
    }

    #[test]
    fn test_dictionary_english_name() {
        let det = HeuristicNerDetector::new();
        let spans = det.detect_persons("Passenger Michael Johnson boarded.");
        assert_eq!(spans.len(), 1);
        assert_eq!(spans[0].text, "Michael Johnson");
    }

    #[test]
    fn test_no_false_positive_lowercase() {
        let det = HeuristicNerDetector::new();
        let spans = det.detect_persons("the server is running at full capacity");
        assert!(spans.is_empty());
    }

    #[test]
    fn test_no_false_positive_single_known_name() {
        let det = HeuristicNerDetector::new();
        // Single first name without a following capitalized word — should not match
        let spans = det.detect_persons("Pierre est parti.");
        assert!(spans.is_empty());
    }

    #[test]
    fn test_context_boost() {
        let det = HeuristicNerDetector::new();
        // Without context
        let spans1 = det.detect_persons("Philippe Martin a appelé.");
        // With context
        let spans2 = det.detect_persons("Le passager Philippe Martin a appelé.");
        assert!(!spans1.is_empty());
        assert!(!spans2.is_empty());
        assert!(spans2[0].score > spans1[0].score);
    }

    #[test]
    fn test_multiple_names() {
        let det = HeuristicNerDetector::new();
        let spans = det.detect_persons("M. Dupont et Mme Martin sont arrivés.");
        assert_eq!(spans.len(), 2);
    }

    #[test]
    fn test_title_not_mid_word() {
        let det = HeuristicNerDetector::new();
        // "OMr" should not trigger "Mr" title
        let spans = det.detect_persons("The OMr code was invalid.");
        assert!(spans.is_empty());
    }

    #[test]
    fn test_accented_names() {
        let det = HeuristicNerDetector::new();
        let spans = det.detect_persons("Mme Héloïse Lefèvre est présente.");
        assert_eq!(spans.len(), 1);
        assert_eq!(spans[0].text, "Héloïse Lefèvre");
    }

    #[test]
    fn test_standalone_first_name_with_context() {
        let det = HeuristicNerDetector::new();
        // "User: Alice" — known first name with context keyword nearby
        let spans = det.detect_persons("Body: User: Alice | CC: 4111");
        assert_eq!(spans.len(), 1, "Expected Alice detected: {:?}", spans);
        assert_eq!(spans[0].text, "Alice");
        assert_eq!(spans[0].label, "PERSON");
    }

    #[test]
    fn test_standalone_first_name_no_context() {
        let det = HeuristicNerDetector::new();
        // "Alice" alone without context — should NOT match (too many false positives)
        let spans = det.detect_persons("Alice went to the store.");
        assert!(
            spans.is_empty(),
            "Standalone name without context should not match: {:?}",
            spans
        );
    }

    #[test]
    fn test_allcaps_lastname_detected() {
        let det = HeuristicNerDetector::new();
        let spans = det.detect_persons("Damien DUPONT est développeur.");
        assert_eq!(spans.len(), 1, "Should detect Damien DUPONT: {:?}", spans);
        assert_eq!(spans[0].text, "Damien DUPONT");
    }

    #[test]
    fn test_allcaps_lastname_with_title() {
        let det = HeuristicNerDetector::new();
        let spans = det.detect_persons("M. MARTIN est arrivé.");
        assert_eq!(
            spans.len(),
            1,
            "Should detect MARTIN after title: {:?}",
            spans
        );
        assert_eq!(spans[0].text, "MARTIN");
    }

    #[test]
    fn test_accented_firstname_allcaps_lastname() {
        let det = HeuristicNerDetector::new();
        // Gaël is not in the default first names list, but "Mathilde" is
        let spans = det.detect_persons("Camille BERNARD est directrice RH.");
        assert_eq!(spans.len(), 1, "Should detect Camille BERNARD: {:?}", spans);
        assert_eq!(spans[0].text, "Camille BERNARD");
    }

    #[test]
    fn test_insee_names_loaded() {
        // Verify the INSEE name list is loaded and contains expected names
        assert!(
            INSEE_FIRST_NAMES.len() >= 2000,
            "Expected 2000+ INSEE names, got {}",
            INSEE_FIRST_NAMES.len()
        );
        let names: std::collections::HashSet<&str> = INSEE_FIRST_NAMES.iter().copied().collect();
        assert!(names.contains("Gaël"), "Gaël should be in INSEE names");
        assert!(
            names.contains("Rachida"),
            "Rachida should be in INSEE names"
        );
        assert!(
            names.contains("Jean-Pierre"),
            "Jean-Pierre should be in INSEE names"
        );
        assert!(
            names.contains("Abdoulaye"),
            "Abdoulaye should be in INSEE names"
        );
    }

    #[test]
    fn test_insee_name_detection_previously_missed() {
        // Names that were NOT in the old 350-name list but ARE in INSEE
        let det = HeuristicNerDetector::new();

        // Rachida was missing from old list
        let spans = det.detect_persons("Rachida BENALI a signé le document.");
        assert_eq!(
            spans.len(),
            1,
            "Rachida BENALI should be detected: {:?}",
            spans
        );
        assert_eq!(spans[0].text, "Rachida BENALI");

        // Abdoulaye was missing from old list
        let spans = det.detect_persons("Abdoulaye DIALLO est le nouveau pilote.");
        assert_eq!(
            spans.len(),
            1,
            "Abdoulaye DIALLO should be detected: {:?}",
            spans
        );
        assert_eq!(spans[0].text, "Abdoulaye DIALLO");

        // Nadia was missing from old list
        let spans = det.detect_persons("Nadia FOURNIER est en congé.");
        assert_eq!(
            spans.len(),
            1,
            "Nadia FOURNIER should be detected: {:?}",
            spans
        );
        assert_eq!(spans[0].text, "Nadia FOURNIER");
    }

    #[test]
    fn test_large_input_performance() {
        // Regression test: the old scan-based word position finder was O(n²)
        // because it used text[pos..].find(word) for each word. With 100k words
        // this would take seconds. The linear scan should complete in < 100ms.
        let det = HeuristicNerDetector::new();
        let chunk = "The server is running well and processing requests normally. ";
        let large_text = chunk.repeat(10_000);
        let start = std::time::Instant::now();
        let _ = det.detect_persons(&large_text);
        let elapsed = start.elapsed();
        assert!(
            elapsed.as_millis() < 1000,
            "Heuristic NER took {}ms on ~600KB input, expected < 1000ms",
            elapsed.as_millis()
        );
    }
}
