#!/usr/bin/env python3
"""Download INSEE first names data and generate a Rust const array.

Usage:
    uv run scripts/build_names.py --top 2000 > src/ner/names_insee.rs

Data source: INSEE Fichier des prénoms (Licence Ouverte v2.0)
https://www.insee.fr/fr/statistiques/8595130
"""

import argparse
import csv
import io
import sys
import zipfile
from collections import defaultdict
from pathlib import Path
from urllib.request import urlretrieve

INSEE_URL = "https://www.insee.fr/fr/statistiques/fichier/8595130/prenoms-2024-nat_csv.zip"
CACHE_DIR = Path.home() / ".cache" / "anon-build"

# Common accent restorations for French names.
# INSEE data is ALL-CAPS without accents; this maps unaccented -> accented forms.
ACCENT_MAP: dict[str, str] = {
    "Adele": "Adèle",
    "Agnes": "Agnès",
    "Aimee": "Aimée",
    "Aime": "Aimé",
    "Amelie": "Amélie",
    "Anais": "Anaïs",
    "Andre": "André",
    "Andree": "Andrée",
    "Angelique": "Angélique",
    "Ariele": "Arièle",
    "Aurelien": "Aurélien",
    "Aurelie": "Aurélie",
    "Beatrice": "Béatrice",
    "Benedicte": "Bénédicte",
    "Benoit": "Benoît",
    "Berenice": "Bérénice",
    "Cecile": "Cécile",
    "Cedric": "Cédric",
    "Celine": "Céline",
    "Chloe": "Chloé",
    "Clement": "Clément",
    "Clemence": "Clémence",
    "Desiree": "Désirée",
    "Desire": "Désiré",
    "Edith": "Édith",
    "Eleonore": "Éléonore",
    "Eliane": "Éliane",
    "Elisabeth": "Élisabeth",
    "Elise": "Élise",
    "Elodie": "Élodie",
    "Eloise": "Éloïse",
    "Emile": "Émile",
    "Emilie": "Émilie",
    "Eric": "Éric",
    "Etienne": "Étienne",
    "Eugene": "Eugène",
    "Eve": "Ève",
    "Evelyne": "Évelyne",
    "Frederic": "Frédéric",
    "Frederique": "Frédérique",
    "Gael": "Gaël",
    "Gaelle": "Gaëlle",
    "Gerald": "Gérald",
    "Gerard": "Gérard",
    "Gregoire": "Grégoire",
    "Gregory": "Grégory",
    "Helene": "Hélène",
    "Heloise": "Héloïse",
    "Herve": "Hervé",
    "Ines": "Inès",
    "Irene": "Irène",
    "Jerome": "Jérôme",
    "Joel": "Joël",
    "Joelle": "Joëlle",
    "Josee": "Josée",
    "Laetitia": "Laëtitia",
    "Lea": "Léa",
    "Leon": "Léon",
    "Leonie": "Léonie",
    "Leopold": "Léopold",
    "Madeleine": "Madeleine",
    "Maelle": "Maëlle",
    "Mael": "Maël",
    "Michele": "Michèle",
    "Noel": "Noël",
    "Noemie": "Noémie",
    "Oceane": "Océane",
    "Ophelie": "Ophélie",
    "Raphael": "Raphaël",
    "Regine": "Régine",
    "Remi": "Rémi",
    "Rene": "René",
    "Renee": "Renée",
    "Sebastien": "Sébastien",
    "Severine": "Séverine",
    "Stephane": "Stéphane",
    "Stephanie": "Stéphanie",
    "Therese": "Thérèse",
    "Valerie": "Valérie",
    "Veronique": "Véronique",
    "Zoe": "Zoé",
    "Nadege": "Nadège",
}


def download_insee_csv() -> Path:
    """Download and cache the INSEE CSV zip file."""
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    zip_path = CACHE_DIR / "prenoms-2024-nat_csv.zip"
    if not zip_path.exists():
        print(f"Downloading INSEE data to {zip_path}...", file=sys.stderr)
        urlretrieve(INSEE_URL, zip_path)
    return zip_path


def parse_insee_csv(zip_path: Path) -> dict[str, int]:
    """Parse the INSEE CSV and return {name: total_count}."""
    counts: dict[str, int] = defaultdict(int)
    with zipfile.ZipFile(zip_path) as zf:
        csv_names = [n for n in zf.namelist() if n.endswith(".csv")]
        if not csv_names:
            raise RuntimeError(f"No CSV file found in {zip_path}")
        csv_name = csv_names[0]
        print(f"Reading {csv_name}...", file=sys.stderr)
        with zf.open(csv_name) as f:
            reader = csv.DictReader(io.TextIOWrapper(f, encoding="utf-8"), delimiter=";")
            for row in reader:
                name = (row.get("preusuel") or row.get("prenom") or "").strip()
                count_str = (row.get("nombre") or row.get("valeur") or "0").strip()
                if name in ("_PRENOMS_RARES", "") or len(name) < 2:
                    continue
                try:
                    count = int(count_str)
                except ValueError:
                    continue
                counts[name] += count
    return dict(counts)


def to_title_case(name: str) -> str:
    """Convert ALL-CAPS INSEE name to title case, handling hyphens.

    JEAN-PIERRE -> Jean-Pierre
    MARIE -> Marie
    """
    parts = name.split("-")
    return "-".join(p.capitalize() for p in parts)


def generate_rust_array(names: list[str], var_name: str = "INSEE_FIRST_NAMES") -> str:
    """Generate a Rust const array from a list of names."""
    lines = [
        f"/// Top {len(names)} French first names from INSEE (Fichier des prénoms, 1900-2024).",
        "/// Source: https://www.insee.fr/fr/statistiques/8595130",
        "/// License: Licence Ouverte v2.0",
        "/// Generated by scripts/build_names.py",
        f"pub const {var_name}: &[&str] = &[",
    ]

    # Format 4 names per line for readability
    for i in range(0, len(names), 4):
        chunk = names[i : i + 4]
        entries = ", ".join(f'"{n}"' for n in chunk)
        lines.append(f"    {entries},")

    lines.append("];")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Generate Rust const array from INSEE first names")
    parser.add_argument("--top", type=int, default=2000, help="Number of top names to include (default: 2000)")
    parser.add_argument("--var", default="INSEE_FIRST_NAMES", help="Rust variable name")
    args = parser.parse_args()

    zip_path = download_insee_csv()
    counts = parse_insee_csv(zip_path)
    print(f"Found {len(counts)} unique names", file=sys.stderr)

    # Sort by count descending, take top N
    sorted_names = sorted(counts.items(), key=lambda x: x[1], reverse=True)
    top_names = sorted_names[: args.top]

    # Convert to title case and apply accent map
    result_names: list[str] = []
    seen: set[str] = set()
    for raw_name, count in top_names:
        title = to_title_case(raw_name)
        accented = ACCENT_MAP.get(title)

        # Add both accented and unaccented if different
        if accented and accented not in seen:
            result_names.append(accented)
            seen.add(accented)
        if title not in seen:
            result_names.append(title)
            seen.add(title)

    # Sort alphabetically for the final output
    result_names.sort()

    print(f"Generated {len(result_names)} entries (with accent variants)", file=sys.stderr)
    print(generate_rust_array(result_names, args.var))


if __name__ == "__main__":
    main()
